import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Resource Type definition for AWS::Neptune::EventSubscription
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-eventsubscription.html}
 */
export type NeptuneEventSubscriptionProperties = {
  /**
   * A Boolean value; set to true to activate the subscription, set to false to create the subscription but not active it.
   */
  Enabled?: boolean;
  /**
   * A list of event categories for a SourceType that you want to subscribe to. You can see a list of the categories for a given SourceType in the Events topic in the Amazon Neptune User Guide or by using the DescribeEventCategories action.
   */
  EventCategories?: string[];
  /**
   * The Amazon Resource Name (ARN) of the SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it.
   */
  SnsTopicArn: string;
  /**
   * The list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. An identifier must begin with a letter and must contain only ASCII letters, digits, and hyphens; it cannot end with a hyphen or contain two consecutive hyphens.
   */
  SourceIds?: string[];
  /**
   * The type of source that will be generating the events. For example, if you want to be notified of events generated by a DB instance, you would set this parameter to db-instance. if this value is not specified, all events are returned.
   */
  SourceType?: string;
  /**
   * The name of the subscription.
   * @maxLength `255`
   */
  SubscriptionName?: string;
  /**
   * An array of key-value pairs to apply to this resource.
   */
  Tags?: Tag[];
};
/**
 * Type definition for `AWS::Neptune::EventSubscription.Tag`.
 * A key-value pair to associate with a resource.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-neptune-eventsubscription-tag.html}
 */
export type Tag = {
  Key: string;
  Value: string;
};
/**
 * Resource Type definition for AWS::Neptune::EventSubscription
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-eventsubscription.html}
 */
export class NeptuneEventSubscription extends $Resource<
  "AWS::Neptune::EventSubscription",
  NeptuneEventSubscriptionProperties,
  Record<string, never>
> {
  public static readonly Type = "AWS::Neptune::EventSubscription";
  constructor(
    logicalId: string,
    properties: NeptuneEventSubscriptionProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, NeptuneEventSubscription.Type, properties, options);
  }
}
