import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * The AWS::NeptuneGraph::PrivateGraphEndpoint resource creates an Amazon NeptuneGraph PrivateGraphEndpoint.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptunegraph-privategraphendpoint.html}
 */
export type NeptuneGraphPrivateGraphEndpointProperties = {
  /**
   * The auto-generated Graph Id assigned by the service.
   */
  GraphIdentifier: string;
  /**
   * The security group Ids associated with the VPC where you want the private graph endpoint to be created, ie, the graph will be reachable from within the VPC.
   */
  SecurityGroupIds?: string[];
  /**
   * The subnet Ids associated with the VPC where you want the private graph endpoint to be created, ie, the graph will be reachable from within the VPC.
   */
  SubnetIds?: string[];
  /**
   * The VPC where you want the private graph endpoint to be created, ie, the graph will be reachable from within the VPC.
   */
  VpcId: string;
};
/**
 * Attribute type definition for `AWS::NeptuneGraph::PrivateGraphEndpoint`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptunegraph-privategraphendpoint.html#aws-resource-neptunegraph-privategraphendpoint-return-values}
 */
export type NeptuneGraphPrivateGraphEndpointAttributes = {
  /**
     * PrivateGraphEndpoint resource identifier generated by concatenating the associated GraphIdentifier and VpcId with an underscore separator.
    
     For example, if GraphIdentifier is `g-12a3bcdef4` and VpcId is `vpc-0a12bc34567de8f90`, the generated PrivateGraphEndpointIdentifier will be `g-12a3bcdef4_vpc-0a12bc34567de8f90`
     */
  PrivateGraphEndpointIdentifier: string;
  /**
   * VPC endpoint that provides a private connection between the Graph and specified VPC.
   */
  VpcEndpointId: string;
};
/**
 * The AWS::NeptuneGraph::PrivateGraphEndpoint resource creates an Amazon NeptuneGraph PrivateGraphEndpoint.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptunegraph-privategraphendpoint.html}
 */
export class NeptuneGraphPrivateGraphEndpoint extends $Resource<
  "AWS::NeptuneGraph::PrivateGraphEndpoint",
  NeptuneGraphPrivateGraphEndpointProperties,
  NeptuneGraphPrivateGraphEndpointAttributes
> {
  public static readonly Type = "AWS::NeptuneGraph::PrivateGraphEndpoint";
  constructor(
    logicalId: string,
    properties: NeptuneGraphPrivateGraphEndpointProperties,
    options?: $ResourceOptions,
  ) {
    super(
      logicalId,
      NeptuneGraphPrivateGraphEndpoint.Type,
      properties,
      options,
    );
  }
}
