import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Resource Type definition for AWS::CodePipeline::Webhook
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-webhook.html}
 */
export type CodePipelineWebhookProperties = {
  /**
   * Supported options are GITHUB_HMAC, IP, and UNAUTHENTICATED.
   */
  Authentication: "GITHUB_HMAC" | "IP" | "UNAUTHENTICATED";
  /**
   * Properties that configure the authentication applied to incoming webhook trigger requests
   */
  AuthenticationConfiguration: WebhookAuthConfiguration;
  /**
   * A list of rules applied to the body/payload sent in the POST request to a webhook URL
   */
  Filters: WebhookFilterRule[];
  /**
   * The name of the webhook
   * @minLength `1`
   * @maxLength `100`
   * @pattern `[A-Za-z0-9.@\-_]+`
   */
  Name?: string;
  /**
   * Configures a connection between the webhook that was created and the external tool with events to be detected.
   */
  RegisterWithThirdParty?: boolean;
  /**
   * The name of the action in a pipeline you want to connect to the webhook.
   * @minLength `1`
   * @maxLength `100`
   * @pattern `[A-Za-z0-9.@\-_]+`
   */
  TargetAction: string;
  /**
   * The name of the pipeline you want to connect to the webhook.
   * @minLength `1`
   * @maxLength `100`
   * @pattern `[A-Za-z0-9.@\-_]+`
   */
  TargetPipeline: string;
  /**
   * The version number of the pipeline to be connected to the trigger request.
   */
  TargetPipelineVersion?: number;
};
/**
 * Attribute type definition for `AWS::CodePipeline::Webhook`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-webhook.html#aws-resource-codepipeline-webhook-return-values}
 */
export type CodePipelineWebhookAttributes = {
  /**
   * logical id of the webhook
   */
  Id: string;
  /**
   * The webhook URL generated by AWS CodePipeline
   */
  Url: string;
};
/**
 * Type definition for `AWS::CodePipeline::Webhook.WebhookAuthConfiguration`.
 * Properties that configure the authentication applied to incoming webhook trigger requests
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-webhook-webhookauthconfiguration.html}
 */
export type WebhookAuthConfiguration = {
  /**
   * The property used to configure acceptance of webhooks in an IP address range. For IP, only the AllowedIPRange property must be set. This property must be set to a valid CIDR range.
   * @minLength `1`
   * @maxLength `100`
   */
  AllowedIPRange?: string;
  /**
   * The property used to configure GitHub authentication. For GITHUB_HMAC, only the SecretToken property must be set.
   * @minLength `1`
   * @maxLength `100`
   */
  SecretToken?: string;
};
/**
 * Type definition for `AWS::CodePipeline::Webhook.WebhookFilterRule`.
 * A list of rules applied to the body/payload sent in the POST request to a webhook URL. All defined rules must pass for the request to be accepted and the pipeline started.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-webhook-webhookfilterrule.html}
 */
export type WebhookFilterRule = {
  /**
   * A JsonPath expression that is applied to the body/payload of the webhook. The value selected by the JsonPath expression must match the value specified in the MatchEquals field. Otherwise, the request is ignored.
   * @minLength `1`
   * @maxLength `150`
   */
  JsonPath: string;
  /**
   * The value selected by the JsonPath expression must match what is supplied in the MatchEquals field. Otherwise, the request is ignored.
   * @minLength `1`
   * @maxLength `150`
   */
  MatchEquals?: string;
};
/**
 * Resource Type definition for AWS::CodePipeline::Webhook
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-webhook.html}
 */
export class CodePipelineWebhook extends $Resource<
  "AWS::CodePipeline::Webhook",
  CodePipelineWebhookProperties,
  CodePipelineWebhookAttributes
> {
  public static readonly Type = "AWS::CodePipeline::Webhook";
  constructor(
    logicalId: string,
    properties: CodePipelineWebhookProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, CodePipelineWebhook.Type, properties, options);
  }
}
