import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Resource type definition for `AWS::AppSync::Api`.
 * Resource schema for AppSync Api
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-api.html}
 */
export type AppSyncApiProperties = {
  /**
   * The configuration for an Event Api
   */
  EventConfig?: EventConfig;
  /**
   * The name of the AppSync API.
   * @minLength `1`
   * @maxLength `50`
   * @pattern `[A-Za-z0-9_\-\ ]+`
   */
  Name: string;
  /**
   * The owner contact information for an API resource.
   * @minLength `1`
   * @maxLength `250`
   * @pattern `[A-Za-z0-9_\-\ \.]+`
   */
  OwnerContact?: string;
  /**
   * An arbitrary set of tags (key-value pairs) for this AppSync API.
   */
  Tags?: Tag[];
};
/**
 * Attribute type definition for `AWS::AppSync::Api`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-api.html#aws-resource-appsync-api-return-values}
 */
export type AppSyncApiAttributes = {
  /**
   * The Amazon Resource Name (ARN) of the AppSync Api
   */
  ApiArn: string;
  /**
   * The unique identifier for the AppSync Api generated by the service
   */
  ApiId: string;
  /**
   * A map of DNS names for the AppSync API.
   */
  Dns: {
    Http: string;
    Realtime: string;
  };
};
/**
 * Type definition for `AWS::AppSync::Api.AuthenticationType`.
 * Security configuration for your AppSync API.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-authenticationtype.html}
 */
export type AuthenticationType =
  | "AMAZON_COGNITO_USER_POOLS"
  | "AWS_IAM"
  | "API_KEY"
  | "OPENID_CONNECT"
  | "AWS_LAMBDA";
/**
 * Type definition for `AWS::AppSync::Api.AuthMode`.
 * An auth mode.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-authmode.html}
 */
export type AuthMode = {
  /**
   * Security configuration for your AppSync API.
   */
  AuthType?: AuthenticationType;
};
/**
 * Type definition for `AWS::AppSync::Api.AuthProvider`.
 * An auth provider for the AppSync API.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-authprovider.html}
 */
export type AuthProvider = {
  /**
   * Security configuration for your AppSync API.
   */
  AuthType: AuthenticationType;
  /**
   * Optional authorization configuration for using Amazon Cognito user pools with your API endpoint.
   */
  CognitoConfig?: CognitoConfig;
  /**
   * A LambdaAuthorizerConfig holds configuration on how to authorize AWS AppSync API access when using the AWS_LAMBDA authorizer mode. Be aware that an AWS AppSync API may have only one Lambda authorizer configured at a time.
   */
  LambdaAuthorizerConfig?: LambdaAuthorizerConfig;
  /**
   * The OpenID Connect configuration.
   */
  OpenIDConnectConfig?: OpenIDConnectConfig;
};
/**
 * Type definition for `AWS::AppSync::Api.CognitoConfig`.
 * Optional authorization configuration for using Amazon Cognito user pools with your API endpoint.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-cognitoconfig.html}
 */
export type CognitoConfig = {
  AppIdClientRegex?: string;
  AwsRegion: string;
  UserPoolId: string;
};
/**
 * Type definition for `AWS::AppSync::Api.EventConfig`.
 * The configuration for an Event Api
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-eventconfig.html}
 */
export type EventConfig = {
  /**
   * A list of auth providers for the AppSync API.
   */
  AuthProviders: AuthProvider[];
  /**
   * A list of auth modes for the AppSync API.
   */
  ConnectionAuthModes: AuthMode[];
  /**
   * A list of auth modes for the AppSync API.
   */
  DefaultPublishAuthModes: AuthMode[];
  /**
   * A list of auth modes for the AppSync API.
   */
  DefaultSubscribeAuthModes: AuthMode[];
  /**
   * The log config for the AppSync API.
   */
  LogConfig?: EventLogConfig;
};
/**
 * Type definition for `AWS::AppSync::Api.EventLogConfig`.
 * The log config for the AppSync API.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-eventlogconfig.html}
 */
export type EventLogConfig = {
  CloudWatchLogsRoleArn: string;
  /**
   * Logging level for the AppSync API.
   */
  LogLevel: EventLogLevel;
};
/**
 * Type definition for `AWS::AppSync::Api.EventLogLevel`.
 * Logging level for the AppSync API.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-eventloglevel.html}
 */
export type EventLogLevel = "NONE" | "ERROR" | "ALL" | "INFO" | "DEBUG";
/**
 * Type definition for `AWS::AppSync::Api.LambdaAuthorizerConfig`.
 * A LambdaAuthorizerConfig holds configuration on how to authorize AWS AppSync API access when using the AWS_LAMBDA authorizer mode. Be aware that an AWS AppSync API may have only one Lambda authorizer configured at a time.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-lambdaauthorizerconfig.html}
 */
export type LambdaAuthorizerConfig = {
  /**
   * @min `0`
   * @max `3600`
   */
  AuthorizerResultTtlInSeconds?: number;
  AuthorizerUri: string;
  IdentityValidationExpression?: string;
};
/**
 * Type definition for `AWS::AppSync::Api.OpenIDConnectConfig`.
 * The OpenID Connect configuration.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-openidconnectconfig.html}
 */
export type OpenIDConnectConfig = {
  AuthTTL?: number;
  ClientId?: string;
  IatTTL?: number;
  Issuer: string;
};
/**
 * Type definition for `AWS::AppSync::Api.Tag`.
 * An arbitrary set of tags (key-value pairs) for this AppSync API.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-api-tag.html}
 */
export type Tag = {
  /**
   * A string used to identify this tag. You can specify a maximum of 128 characters for a tag key.
   * @minLength `1`
   * @maxLength `128`
   * @pattern `^(?!aws:)[ a-zA-Z+-=._:/]+$`
   */
  Key: string;
  /**
   * A string containing the value for this tag. You can specify a maximum of 256 characters for a tag value.
   * @minLength `0`
   * @maxLength `256`
   * @pattern `^[\s\w+-=\.:/@]*$`
   */
  Value: string;
};
/**
 * Resource type definition for `AWS::AppSync::Api`.
 * Resource schema for AppSync Api
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-api.html}
 */
export class AppSyncApi extends $Resource<
  "AWS::AppSync::Api",
  AppSyncApiProperties,
  AppSyncApiAttributes
> {
  public static readonly Type = "AWS::AppSync::Api";
  constructor(
    logicalId: string,
    properties: AppSyncApiProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, AppSyncApi.Type, properties, options);
  }
}
