import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Resource Type definition for AWS::SecurityLake::DataLake
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-securitylake-datalake.html}
 */
export type SecurityLakeDataLakeProperties = {
  /**
   * Provides encryption details of Amazon Security Lake object.
   */
  EncryptionConfiguration?: EncryptionConfiguration;
  /**
   * Provides lifecycle details of Amazon Security Lake object.
   */
  LifecycleConfiguration?: LifecycleConfiguration;
  /**
   * The Amazon Resource Name (ARN) used to index AWS Glue table partitions that are generated by the ingestion and normalization of AWS log sources and custom sources.
   * @pattern `^arn:.*$`
   */
  MetaStoreManagerRoleArn?: string;
  /**
   * Provides replication details of Amazon Security Lake object.
   */
  ReplicationConfiguration?: ReplicationConfiguration;
  Tags?: Tag[];
};
/**
 * Attribute type definition for `AWS::SecurityLake::DataLake`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-securitylake-datalake.html#aws-resource-securitylake-datalake-return-values}
 */
export type SecurityLakeDataLakeAttributes = {
  /**
   * The Amazon Resource Name (ARN) created by you to provide to the subscriber.
   * @minLength `1`
   * @maxLength `1011`
   */
  Arn: string;
  /**
   * The ARN for the Amazon Security Lake Amazon S3 bucket.
   */
  S3BucketArn: string;
};
/**
 * Type definition for `AWS::SecurityLake::DataLake.EncryptionConfiguration`.
 * Provides encryption details of Amazon Security Lake object.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-securitylake-datalake-encryptionconfiguration.html}
 */
export type EncryptionConfiguration = {
  /**
   * The id of KMS encryption key used by Amazon Security Lake to encrypt the Security Lake object.
   */
  KmsKeyId?: string;
};
/**
 * Type definition for `AWS::SecurityLake::DataLake.Expiration`.
 * Provides data expiration details of Amazon Security Lake object.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-securitylake-datalake-expiration.html}
 */
export type Expiration = {
  /**
   * Number of days before data expires in the Amazon Security Lake object.
   * @min `1`
   */
  Days?: number;
};
/**
 * Type definition for `AWS::SecurityLake::DataLake.LifecycleConfiguration`.
 * Provides lifecycle details of Amazon Security Lake object.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-securitylake-datalake-lifecycleconfiguration.html}
 */
export type LifecycleConfiguration = {
  /**
   * Provides data expiration details of Amazon Security Lake object.
   */
  Expiration?: Expiration;
  /**
   * Provides data storage transition details of Amazon Security Lake object.
   */
  Transitions?: Transitions[];
};
/**
 * Type definition for `AWS::SecurityLake::DataLake.ReplicationConfiguration`.
 * Provides replication details of Amazon Security Lake object.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-securitylake-datalake-replicationconfiguration.html}
 */
export type ReplicationConfiguration = {
  /**
   * Replication enables automatic, asynchronous copying of objects across Amazon S3 buckets. Amazon S3 buckets that are configured for object replication can be owned by the same AWS account or by different accounts. You can replicate objects to a single destination bucket or to multiple destination buckets. The destination buckets can be in different AWS Regions or within the same Region as the source bucket.
   */
  Regions?: string[];
  /**
   * Replication settings for the Amazon S3 buckets. This parameter uses the AWS Identity and Access Management (IAM) role you created that is managed by Security Lake, to ensure the replication setting is correct.
   * @pattern `^arn:.*$`
   */
  RoleArn?: string;
};
/**
 * Type definition for `AWS::SecurityLake::DataLake.Tag`.
 * A key-value pair to associate with a resource.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-securitylake-datalake-tag.html}
 */
export type Tag = {
  /**
   * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, `_`, `.`, `/`, `=`, `+`, and `-`.
   */
  Key: string;
  /**
   * The value for the tag. You can specify a value that is 0 to 256 characters in length.
   */
  Value: string;
};
/**
 * Type definition for `AWS::SecurityLake::DataLake.Transitions`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-securitylake-datalake-transitions.html}
 */
export type Transitions = {
  /**
   * Number of days before data transitions to a different S3 Storage Class in the Amazon Security Lake object.
   * @min `1`
   */
  Days?: number;
  /**
   * The range of storage classes that you can choose from based on the data access, resiliency, and cost requirements of your workloads.
   */
  StorageClass?: string;
};
/**
 * Resource Type definition for AWS::SecurityLake::DataLake
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-securitylake-datalake.html}
 */
export class SecurityLakeDataLake extends $Resource<
  "AWS::SecurityLake::DataLake",
  SecurityLakeDataLakeProperties,
  SecurityLakeDataLakeAttributes
> {
  public static readonly Type = "AWS::SecurityLake::DataLake";
  constructor(
    logicalId: string,
    properties: SecurityLakeDataLakeProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, SecurityLakeDataLake.Type, properties, options);
  }
}
