import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Schema for AWS::ApiGatewayV2::RoutingRule
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-routingrule.html}
 */
export type ApiGatewayV2RoutingRuleProperties = {
  Actions: Action[];
  Conditions: Condition[];
  /**
   * The amazon resource name (ARN) of the domain name resource.
   */
  DomainNameArn: string;
  Priority: number;
};
/**
 * Attribute type definition for `AWS::ApiGatewayV2::RoutingRule`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-routingrule.html#aws-resource-apigatewayv2-routingrule-return-values}
 */
export type ApiGatewayV2RoutingRuleAttributes = {
  /**
   * Amazon Resource Name (ARN) of the resource.
   */
  RoutingRuleArn: string;
  /**
   * RoutingRule Id generated by service
   */
  RoutingRuleId: string;
};
/**
 * Type definition for `AWS::ApiGatewayV2::RoutingRule.Action`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-routingrule-action.html}
 */
export type Action = {
  InvokeApi: ActionInvokeApi;
};
/**
 * Type definition for `AWS::ApiGatewayV2::RoutingRule.ActionInvokeApi`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-routingrule-actioninvokeapi.html}
 */
export type ActionInvokeApi = {
  ApiId: string;
  Stage: string;
  StripBasePath?: boolean;
};
/**
 * Type definition for `AWS::ApiGatewayV2::RoutingRule.Condition`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-routingrule-condition.html}
 */
export type Condition = {
  MatchBasePaths?: MatchBasePaths;
  MatchHeaders?: MatchHeaders;
};
/**
 * Type definition for `AWS::ApiGatewayV2::RoutingRule.MatchBasePaths`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-routingrule-matchbasepaths.html}
 */
export type MatchBasePaths = {
  AnyOf: string[];
};
/**
 * Type definition for `AWS::ApiGatewayV2::RoutingRule.MatchHeaders`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-routingrule-matchheaders.html}
 */
export type MatchHeaders = {
  AnyOf: MatchHeaderValue[];
};
/**
 * Type definition for `AWS::ApiGatewayV2::RoutingRule.MatchHeaderValue`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-routingrule-matchheadervalue.html}
 */
export type MatchHeaderValue = {
  Header: string;
  ValueGlob: string;
};
/**
 * Schema for AWS::ApiGatewayV2::RoutingRule
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-routingrule.html}
 */
export class ApiGatewayV2RoutingRule extends $Resource<
  "AWS::ApiGatewayV2::RoutingRule",
  ApiGatewayV2RoutingRuleProperties,
  ApiGatewayV2RoutingRuleAttributes
> {
  public static readonly Type = "AWS::ApiGatewayV2::RoutingRule";
  constructor(
    logicalId: string,
    properties: ApiGatewayV2RoutingRuleProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, ApiGatewayV2RoutingRule.Type, properties, options);
  }
}
