import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Resource type definition for `AWS::MemoryDB::MultiRegionCluster`.
 * The AWS::MemoryDB::Multi Region Cluster resource creates an Amazon MemoryDB Multi Region Cluster.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-memorydb-multiregioncluster.html}
 */
export type MemoryDBMultiRegionClusterProperties = {
  /**
   * Description of the multi region cluster.
   */
  Description?: string;
  /**
   * The engine type used by the multi region cluster.
   */
  Engine?: string;
  /**
   * The Redis engine version used by the multi region cluster.
   */
  EngineVersion?: string;
  /**
   * The name of the Multi Region cluster. This value must be unique as it also serves as the multi region cluster identifier.
   * @pattern `[a-z][a-z0-9\-]*`
   */
  MultiRegionClusterNameSuffix?: string;
  /**
   * The name of the parameter group associated with the multi region cluster.
   */
  MultiRegionParameterGroupName?: string;
  /**
   * The compute and memory capacity of the nodes in the multi region cluster.
   */
  NodeType: string;
  /**
   * The number of shards the multi region cluster will contain.
   */
  NumShards?: number;
  /**
     * A flag that enables in-transit encryption when set to true.
    
    You cannot modify the value of TransitEncryptionEnabled after the cluster is created. To enable in-transit encryption on a cluster you must set TransitEncryptionEnabled to true when you create a cluster.
     */
  TLSEnabled?: boolean;
  /**
   * An array of key-value pairs to apply to this multi region cluster.
   * @maxLength `50`
   */
  Tags?: Tag[];
  /**
   * An enum string value that determines the update strategy for scaling. Possible values are 'COORDINATED' and 'UNCOORDINATED'. Default is 'COORDINATED'.
   */
  UpdateStrategy?: "COORDINATED" | "UNCOORDINATED";
};
/**
 * Attribute type definition for `AWS::MemoryDB::MultiRegionCluster`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-memorydb-multiregioncluster.html#aws-resource-memorydb-multiregioncluster-return-values}
 */
export type MemoryDBMultiRegionClusterAttributes = {
  /**
   * The Amazon Resource Name (ARN) of the multi region cluster.
   */
  ARN: string;
  /**
   * The name of the Global Datastore, it is generated by MemoryDB adding a prefix to MultiRegionClusterNameSuffix.
   */
  MultiRegionClusterName: string;
  /**
   * The status of the multi region cluster. For example, Available, Updating, Creating.
   */
  Status: string;
};
/**
 * Type definition for `AWS::MemoryDB::MultiRegionCluster.Tag`.
 * A key-value pair to associate with a resource.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-memorydb-multiregioncluster-tag.html}
 */
export type Tag = {
  /**
   * The key for the tag. May not be null.
   * @minLength `1`
   * @maxLength `128`
   * @pattern `^(?!aws:)(?!memorydb:)[a-zA-Z0-9 _\.\/=+:\-@]{1,128}$`
   */
  Key: string;
  /**
   * The tag's value. May be null.
   * @minLength `1`
   * @maxLength `256`
   * @pattern `^(?!aws:)(?!memorydb:)[a-zA-Z0-9 _\.\/=+:\-@]{1,256}$`
   */
  Value: string;
};
/**
 * Resource type definition for `AWS::MemoryDB::MultiRegionCluster`.
 * The AWS::MemoryDB::Multi Region Cluster resource creates an Amazon MemoryDB Multi Region Cluster.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-memorydb-multiregioncluster.html}
 */
export class MemoryDBMultiRegionCluster extends $Resource<
  "AWS::MemoryDB::MultiRegionCluster",
  MemoryDBMultiRegionClusterProperties,
  MemoryDBMultiRegionClusterAttributes
> {
  public static readonly Type = "AWS::MemoryDB::MultiRegionCluster";
  constructor(
    logicalId: string,
    properties: MemoryDBMultiRegionClusterProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, MemoryDBMultiRegionCluster.Type, properties, options);
  }
}
