import { Resource as $Resource } from "@awboost/cfn-template-builder/template/resource";
import type { ResourceOptions as $ResourceOptions } from "@awboost/cfn-template-builder/template";
/**
 * Resource Type definition for AWS::Lambda::Alias
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html}
 */
export type LambdaAliasProperties = {
  /**
   * A description of the alias.
   */
  Description?: string;
  /**
   * The name of the Lambda function.
   */
  FunctionName: string;
  /**
   * The function version that the alias invokes.
   */
  FunctionVersion: string;
  /**
   * The name of the alias.
   */
  Name: string;
  /**
   * Specifies a provisioned concurrency configuration for a function's alias.
   */
  ProvisionedConcurrencyConfig?: ProvisionedConcurrencyConfiguration;
  /**
   * The routing configuration of the alias.
   */
  RoutingConfig?: AliasRoutingConfiguration;
};
/**
 * Attribute type definition for `AWS::Lambda::Alias`.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html#aws-resource-lambda-alias-return-values}
 */
export type LambdaAliasAttributes = {
  /**
   * Lambda Alias ARN generated by the service.
   */
  AliasArn: string;
};
/**
 * Type definition for `AWS::Lambda::Alias.AliasRoutingConfiguration`.
 * The traffic-shifting configuration of a Lambda function alias.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-alias-aliasroutingconfiguration.html}
 */
export type AliasRoutingConfiguration = {
  /**
   * The second version, and the percentage of traffic that's routed to it.
   */
  AdditionalVersionWeights?: VersionWeight[];
};
/**
 * Type definition for `AWS::Lambda::Alias.ProvisionedConcurrencyConfiguration`.
 * A provisioned concurrency configuration for a function's alias.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-alias-provisionedconcurrencyconfiguration.html}
 */
export type ProvisionedConcurrencyConfiguration = {
  /**
   * The amount of provisioned concurrency to allocate for the alias.
   */
  ProvisionedConcurrentExecutions: number;
};
/**
 * Type definition for `AWS::Lambda::Alias.VersionWeight`.
 * The traffic-shifting configuration of a Lambda function alias.
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-alias-versionweight.html}
 */
export type VersionWeight = {
  /**
   * The qualifier of the second version.
   */
  FunctionVersion: string;
  /**
   * The percentage of traffic that the alias routes to the second version.
   */
  FunctionWeight: number;
};
/**
 * Resource Type definition for AWS::Lambda::Alias
 * @see {@link https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html}
 */
export class LambdaAlias extends $Resource<
  "AWS::Lambda::Alias",
  LambdaAliasProperties,
  LambdaAliasAttributes
> {
  public static readonly Type = "AWS::Lambda::Alias";
  constructor(
    logicalId: string,
    properties: LambdaAliasProperties,
    options?: $ResourceOptions,
  ) {
    super(logicalId, LambdaAlias.Type, properties, options);
  }
}
